language: cpp
sudo: false
script: scons
compiler: clang
addons:
  apt:
    packages:
      - libc++-dev
      - libgl1-mesa-dev
      - libglew-dev
      - libsfml-dev
      - libfreetype6-dev
      - libjpeg-dev
